### ISSUE TITLE
TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by erickbritto** [thiagociavolela/api-whatsapp#1]
C:\api\api-whatsapp>npm start

> whatsapp-api@1.0.0 start
> node app.js

Api Online na porta: 8000
C:\api\api-whatsapp\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (C:\api\api-whatsapp\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at C:\api\api-whatsapp\node_modules\whatsapp-web.js\src\Client.js:733:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.12.1

C:\api\api-whatsapp>git pull
Already up to date.

C:\api\api-whatsapp>git pull up
fatal: 'up' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by erickbritto** [comment]
isso para mim funcionou...

WEB_VERSION_CACHE_TYPE=local

npm uninstall whatsapp-web.js
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
